version: '3.8'

services:
  # proxy server for routing all inner services
  reverse-proxy:
    image: caddy:2-alpine
    depends_on:
      - blackhole
      - smart
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./secrets/reverse-proxy.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/proxy/config:/config
      - ./data/proxy/data:/data
  
  # local dns for manage mothership.home domain and block ads
  blackhole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    env_file:
      - ./secrets/blackhole.env
    volumes:
      - ./data/blackhole/pihole/:/etc/pihole
      - ./data/blackhole/dnsmasq/:/etc/dnsmasq.d

  # manages automation and control of all iot devices
  smart:
    image: homeassistant/home-assistant:stable
    network_mode: host
    env_file:
      - ./secrets/smart.env
    volumes:
      - ./data/smart:/config

  mqtt:
    build:
      context: ./mqtt
    ports:
      - 1883:1883
    env_file:
      - ./secrets/mqtt.env
    volumes:
      - ./data/mqtt/data:/mosquitto/data
      - ./data/mqtt/log:/mosquitto/log

  # manages torrent downloads
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - 51413:51413
      - 51413:51413/udp
    env_file:
      - ./secrets/transmission.env
    volumes:
      - ./data/transmission:/config
      - /media/data/downloads:/downloads:rw

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    env_file:
      - ./secrets/radarr.env
    volumes:
      - ./data/radarr:/config
      - /media/data/movies:/movies:rw
      - /media/data/downloads:/downloads:rw
  
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    env_file:
      - ./secrets/prowlarr.env
    volumes:
      - ./data/prowlarr:/config
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    env_file:
      - ./secrets/bazarr.env
    volumes:
      - ./data/bazarr/config:/config
      - /media/data/movies:/movies:rw