version: '3.8'

services:
  # proxy server for routing all inner services
  reverse-proxy:
    image: caddy:2-alpine
    depends_on:
      - blackhole
      - smart
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./secrets/reverse-proxy.env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/proxy/config:/config
      - ./data/proxy/data:/data
  
  # local dns for manage mothership.home domain and block ads
  blackhole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    env_file:
      - ./secrets/blackhole.env
    volumes:
      - ./data/blackhole/pihole/:/etc/pihole
      - ./data/blackhole/dnsmasq/:/etc/dnsmasq.d

  # home page for all services
  deck:
    image: lscr.io/linuxserver/heimdall:latest
    env_file:
      - ./secrets/deck.env
    volumes:
      - ./data/deck:/config
  
  # vscode for editing configurations
  code:
    image: lscr.io/linuxserver/code-server:latest
    env_file:
      - ./secrets/code.env
    volumes:
      - ./data/code:/config
      - ./data:/config/workspace

  # manages automation and control of all iot devices
  smart:
    image: homeassistant/home-assistant:stable
    depends_on:
      - mqtt
    network_mode: host
    env_file:
      - ./secrets/smart.env
    volumes:
      - ./data/smart:/config

  mqtt:
    build:
      context: ./mqtt
    ports:
      - 1883:1883
    env_file:
      - ./secrets/mqtt.env
    volumes:
      - ./data/mqtt/data:/mosquitto/data
      - ./data/mqtt/log:/mosquitto/log

  # bridges zigbee devices to mqtt
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    env_file:
      - ./secrets/zigbee2mqtt.env
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_429e93520ed9eb11939a0815b9da5f8b-if00-port0:/dev/ttyACM0
    group_add:
      - dialout

  # manages all esp devices
  esphome:
    image: esphome/esphome
    network_mode: host
    privileged: true
    volumes:
      - ./data/esphome:/config

  # monitors docker images versions
  diun:
    image: crazymax/diun:latest
    depends_on:
      - reverse-proxy
      - blackhole
      - deck
      - code
      - mqtt
      - esphome
      - diunstore
      - files
      - transmission
      - radarr
      - prowlarr
      - bazarr
    build: 
      context: ./diun
    env_file:
      - ./secrets/diun.env
    volumes:
      - "./data/diun:/data"
      - "./diun/config/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

  diunstore:
    image: barvazware/diunstore:latest
    env_file:
      - ./secrets/diunstore.env
    volumes:
      - "./data/diunstore:/data"

############################################################
#
# Media Servers
#
############################################################

  # media files explorar
  files:
    image: filebrowser/filebrowser:s6
    env_file:
      - ./secrets/files.env
    volumes:
      - ./data/files:/database
      - /media/data:/srv:rw

  # manages torrent downloads
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - 51413:51413
      - 51413:51413/udp
    env_file:
      - ./secrets/transmission.env
    volumes:
      - ./data/transmission:/config
      - /media/data/downloads:/downloads:rw

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    env_file:
      - ./secrets/radarr.env
    volumes:
      - ./data/radarr:/config
      - /media/data/movies:/movies:rw
      - /media/data/downloads:/downloads:rw
  
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    env_file:
      - ./secrets/prowlarr.env
    volumes:
      - ./data/prowlarr:/config
  
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    env_file:
      - ./secrets/bazarr.env
    volumes:
      - ./data/bazarr/config:/config
      - /media/data/movies:/movies:rw