version: '3.8'

services:
  reverse-proxy:
    image: caddy:2-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/proxy/config:/config
      - ./data/proxy/data:/data
  
  blackhole:
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    env_file:
      - ./.secrets/blackhole.env
    volumes:
      - ./data/blackhole/pihole/:/etc/pihole
      - ./data/blackhole/dnsmasq/:/etc/dnsmasq.d