esphome:
  name: boltsense-main-door-lock-sensor
  friendly_name: BoltSense main door lock sensor
  on_boot:
    priority: -10
    then:
      - delay: 300ms
      - script.execute: sync_leds

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

packages:
  network: !include common/network.yaml
  telemetry: !include common/telemetry.yaml

binary_sensor:
  - platform: gpio
    id: door_lock
    pin:
      number: GPIO10
      mode:
        input: true
      inverted: true
    filters:
      - delayed_on: 120ms
      - delayed_off: 120ms
    device_class: lock
    on_state:
      then:
        - script.execute: sync_leds
    internal: true
  
  - platform: template
    name: "Door Lock State"
    device_class: lock
    # This sensor will be the OPPOSITE of the GPIO sensor
    lambda: |-
      return !id(door_lock).state;
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

switch:
  - platform: gpio
    id: green_led
    pin: GPIO0
    restore_mode: ALWAYS_OFF
    internal: true

  - platform: gpio
    id: red_led
    pin: GPIO1
    restore_mode: ALWAYS_OFF
    internal: true

script:
  - id: sync_leds
    mode: restart
    then:
      - if:
          condition:
            binary_sensor.is_on: door_lock
          then:
            - switch.turn_on: green_led
            - switch.turn_off: red_led
          else:
            - switch.turn_off: green_led
            - switch.turn_on: red_led