esphome:
  name: horizon-sentinel-1
  friendly_name: Horizon sentinel 1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

packages:
  network: !include common/network.yaml
  telemetry: !include common/telemetry.yaml

bluetooth_proxy: