esphome:
  name: sonoff-s26-2
  friendly_name: sonoff s26 2

esp8266:
  board: esp01_1m

packages:
  network: !include common/network.yaml
  telemetry: !include common/telemetry.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: "relay"

  - platform: restart
    name: "Restart"