name: romulus

include:
  - ./common.yaml

services:
  status:
    image: louislam/uptime-kuma:latest
    env_file:
      - ./envs/common.env
    volumes:
      - kuma_data:/app/data
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    env_file:
      - ./envs/common.env
      - ./envs/dozzle.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle_data:/data
    restart: unless-stopped

  beszel:
    image: henrygd/beszel:latest
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - beszel_data:/beszel_data
    restart: unless-stopped

volumes:
  kuma_data:
  dozzle_data:
  beszel_data:
