name: donnager

include:
  - ./common.yaml

services:
  smart:
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    env_file:
      - ./envs/common.env
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    depends_on:
      - mqtt

  esphome:
    image: ghcr.io/esphome/esphome:stable
    network_mode: host
    privileged: true
    env_file:
      - ./envs/common.env
    volumes:
      - ./esphome/config:/config
      - esphome_build:/config/.esphome
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - smart

  mqtt:
    image: emqx/emqx:latest
    ports:
      - 1883:1883
    env_file:
      - ./envs/common.env
      - ./envs/mqtt.env
    environment:
      - EMQX_NODE__NAME=emqx@donnager
    volumes:
      - mqtt_data:/opt/emqx/data
      - mqtt_log:/opt/emqx/log
    restart: unless-stopped
  
  z2m:
    image: koenkk/zigbee2mqtt:latest
    env_file:
      - ./envs/common.env
    volumes:
      - z2m_data:/app/data
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    depends_on:
      - mqtt

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    env_file:
      - ./envs/common.env
      - ./envs/code.env
    environment:
    - PUID=0
    - PGID=0
    volumes:
      - code_server_data:/config
      - homeassistant_data:/workspace/home-assistant
    restart: unless-stopped

volumes:
  homeassistant_data:
  esphome_build:
  mqtt_data:
  mqtt_log:
  z2m_data:
  code_server_data:
